apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-image-warden.fullname" . }}-controller
  labels:
    {{- include "k8s-image-warden.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.webhook.port }}
    targetPort: webhook
    name: webhook
  - port: {{ .Values.service.grpc.port }}
    targetPort: grpc
    name: controller
  selector:
    {{- include "k8s-image-warden.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: controller