apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "k8s-image-warden.fullname" . }}-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi