# Default values for k8s-image-warden.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

cert-manager:
  enabled: true
  startupapicheck:
    enabled: false

controller:
  replicaCount: 1
  retentionInDays: 30
  rulesConfig: 
    rules:
    - name: docker.io is default registry
      mutate:
        type: DefaultRegistry
        registry: "docker.io"
    - name: no rolling tags
      validate:
        type: RollingTag
        allow: false
    - name: no latests
      validate:
        type: Latest
        allow: false
  image:
    repository: k8s-image-warden-controller
    pullPolicy: Never
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

agent:
  criEndpoint: "/run/containerd/containerd.sock"
  criFetchInterval: 5
  image:
    repository: k8s-image-warden-agent
    pullPolicy: Never
    # Overrides the image tag whose default is the chart appVersion.
    tag: "latest"

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  grpc:
    port: 5000
  webhook:
    port: 8443

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
